ALTER TABLE PRODUS DROP CONSTRAINT FK_PRODUS_CATEGORIE_ID
ALTER TABLE PRODUS DROP CONSTRAINT FK_PRODUS_FURNIZOR_ID
ALTER TABLE PRODUS ADD CONSTRAINT FK_PRODUS_CATEGORIE_ID FOREIGN KEY (categorie_id) REFERENCES CATEGORIE(categorie_id) ON DELETE CASCADE
ALTER TABLE PRODUS ADD CONSTRAINT FK_PRODUS_FURNIZOR_ID FOREIGN KEY (furnizor_id) REFERENCES FURNIZOR(furnizor_id) ON DELETE CASCADE

ALTER TABLE AUTOMOBIL_COMPATIBIL DROP CONSTRAINT FK_AUTO_COMP_AUTOMOBIL_ID
ALTER TABLE AUTOMOBIL_COMPATIBIL DROP CONSTRAINT FK_AUTO_COMP_COD_PRODUS
ALTER TABLE AUTOMOBIL_COMPATIBIL ADD CONSTRAINT FK_AUTO_COMP_AUTOMOBIL_ID FOREIGN KEY (automobil_id) REFERENCES AUTOMOBIL(automobil_id) ON DELETE CASCADE
ALTER TABLE AUTOMOBIL_COMPATIBIL ADD CONSTRAINT FK_AUTO_COMP_COD_PRODUS FOREIGN KEY (cod_produs) REFERENCES PRODUS(cod_produs) ON DELETE CASCADE

ALTER TABLE ADRESA DROP CONSTRAINT FK_ADRESA_CLIENT
ALTER TABLE ADRESA ADD CONSTRAINT FK_ADRESA_CLIENT FOREIGN KEY (client_id) REFERENCES CLIENT(client_id) ON DELETE CASCADE

ALTER TABLE COMANDA DROP CONSTRAINT FK_COMANDA_ADRESA
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_ADRESA FOREIGN KEY (adresa_id) REFERENCES ADRESA(adresa_id) ON DELETE CASCADE

ALTER TABLE PRODUSE_COMANDATE DROP CONSTRAINT FK_PROD_COM_PRODUS
ALTER TABLE PRODUSE_COMANDATE DROP CONSTRAINT FK_PROD_COM_COMANDA
ALTER TABLE PRODUSE_COMANDATE ADD CONSTRAINT FK_PROD_COM_PRODUS FOREIGN KEY (cod_produs) REFERENCES PRODUS(cod_produs) ON DELETE CASCADE
ALTER TABLE PRODUSE_COMANDATE ADD CONSTRAINT FK_PROD_COM_COMANDA FOREIGN KEY (comanda_id) REFERENCES COMANDA(comanda_id) ON DELETE CASCADE
